### ISSUE TITLE
Error with bcrypt on yarn install

### ISSUE THREAD

**Issue by rafaelangical** [dcodeIO/bcrypt.js#105]
I'am receiving a error while install dependencies of project with yarn workspaces.

`error /home/rafael/fullstack-app/node_modules/bcrypt-as-promised/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/rafael/fullstack-app/node_modules/bcrypt-as-promised/node_modules/bcrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.15.3 | linux | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/home/rafael/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
`

node actually v10.5.3, tested too 10.0.0 and 12.0.0
gcc version 8.3.0
yarn version 1.17.3

**Comment by dcodeIO** [comment]
The native one is another module: https://github.com/kelektiv/node.bcrypt.js
