### ISSUE TITLE
node_modules\bcrypt\lib\binding\bcrypt_lib.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by siddiqlm** [dcodeIO/bcrypt.js#112]
I  installed bcrypt in my local machine and it is working fine. But when I deployed the files in the Microsoft Azure I am getting the following error 

> Application has thrown an uncaught exception and is terminated:
> Error: \\?\D:\home\site\wwwroot\node_modules\bcrypt\lib\binding\bcrypt_lib.node is not a valid Win32 application.
> 
> \\?\D:\home\site\wwwroot\node_modules\bcrypt\lib\binding\bcrypt_lib.node
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
>     at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bcrypt\bcrypt.js:6:16)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
>     at Module.load (internal/modules/cjs/loader.js:598:32)

Is there any separate brcypt package available to install with 32-bit node?

I am trying to upgrade it to 64-bit node in Microsoft Azure. But no luck so far. So I decided to try install bcypt package for 32-bit node. Could someone help me with this?

**Comment by dcodeIO** [comment]
[bcrypt](https://www.npmjs.com/package/bcrypt) is a native package, while bcryptjs (this package) is pure JS and should work everywhere.

**Comment by siddiqlm** [comment]
bcryptjs is working great. Thank you so much @dcodeIO .

**Comment by NutonC** [comment]
how solved brother ....i still not solved

**Comment by siddiqlm** [comment]
I used 'bcryptjs' module instead of 'bcrypt' module. It just worked fine. What error you are getting?

**Comment by EdelMacias** [comment]
for anyone having this error, just change
`const bcrypt = require("bcrypt");
`for
`const bcrypt = require("bcryptjs");
`

**Comment by duqaqon** [comment]
> const bcrypt = require("bcryptjs");

Thank you @EdelMacias

**Comment by shajin-sha** [comment]
> for anyone having this error, just change
> `const bcrypt = require("bcrypt"); `for
> `const bcrypt = require("bcryptjs"); `
> and npm i bcryptjs --save

Thank you @EdelMacias

**Comment by GD-50** [comment]
Install
[node-gyp][1]  package globally and then retry `npm i bcrypt`

    npm i -g node-gyp


  [1]: https://www.npmjs.com/package/node-gyp

in my case its work

**Comment by rakeshkumarprajapati** [comment]
5645456**54564**
