### ISSUE TITLE
No new releases in 3 years

### ISSUE THREAD

**Issue by thernstig** [dcodeIO/bcrypt.js#116]
I've read this repos README.md, but cannot get a good grasp on this.

The npm registry https://www.npmjs.com/package/bcryptjs has not been updated in 3 years.
Whereas this other npm repo https://www.npmjs.com/package/bcrypt (which is not a pure js library) receives frequent updates.

So two questions:
1. Since this package has not been updated in 3 years, could it potentially be "unsafe" in any sense? Considering https://www.npmjs.com/package/bcrypt often receives updates but solves the same thing.
2. Is thus, due to the above question, https://www.npmjs.com/package/bcrypt a better choice?

**Comment by dcodeIO** [comment]
It's fine, the algorithm hasn't changed.

**Comment by thernstig** [comment]
Thanks!
