### ISSUE TITLE
Bcrypt compare method is not returning true when hash password is stored in the database.

### ISSUE THREAD

**Issue by Irtiza751** [dcodeIO/bcrypt.js#131]
```javascript
userSchema.statics.findByCredentials = async (email, password) => {
    const user = await User.findOne({ email })

    if (!user) {
        throw new Error('no user found!')
    }

    const isMatch = await bcrypt.compare(password, user.password)

    if (!isMatch) {
        throw new Error('invalid credentials!')
    }

    return user
}
```
The above code is matching the hash password that is stored in the database with a plain text password but it always returns `false`.
so I tried this & it's working, could anyone explain to me; why this code is working & the above one is not working?
```javascript
const bcrypt = require('bcryptjs')
const encription = async () => {
const password = 'abc1234';
console.log('plain password: ', password);

const hashPass = await bcrypt.hash(password, 8);
console.log(`hash password: ${hashPass}`);

const isValidPass = await bcrypt.compare(password, hashPass);
console.log(`is valid: ${isValidPass}`);
}

encription();
```

**Comment by berazo29** [comment]
I did an minimal example on my computer and it works fine. 
Do you mean that 'isMatch' returns false?

**Comment by Irtiza751** [comment]
Yeah, it is returning false for some reason I don't know why, but then I recreated the project from scratch and install all dependencies through ``yarn`` instead of ``npm`` and it started working.

Anyways thank you so much for replying, it feels really good that the community around JavaScript is so responsive & helpful.
