### ISSUE TITLE
Performance vs. C++ bcrypt?

### ISSUE THREAD

**Issue by CamiloMM** [dcodeIO/bcrypt.js#14]
It would be nice to have a table where you list a comparison of the performance of this package vs. [bcrypt](https://www.npmjs.org/package/bcrypt) on the same machine, in the readme.

It doesn't need to be too precise, only something like a header "performance" and a table with different iteration counts and timing of both packages.

**Comment by caub** [comment]
https://repl.it/@caub/bcrypt-perfs newer benchmark
