### ISSUE TITLE
This repository is no longer maintained

### ISSUE THREAD

**Issue by phatify** [dcodeIO/bcrypt.js#140]
Who is maintaining it? 
It has not been updated for a long time, should we trust it to use?

**Comment by masterbater** [comment]
> Who is maintaining it? It has not been updated for a long time, should we trust it to use?

Probably you are misunderstanding but the crypto module provided by browser and node, havent change.
Also there is no dependencies therefore no need for maintenace. Except if crypto module has performance improvements or some security issue.

**Comment by ahkhanjani** [comment]
> It has not been updated for a long time, should we trust it to use?

It's the best you don't use a library last published 7 years ago for security purposes.

**Comment by dcodeIO** [comment]
This is code, not a banana. I'm not aware of any time-induced breakage, hence closing.

**Comment by aggregate1166877** [comment]
> It's the best you don't use a library last published 7 years ago for security purposes.

Actually, it's precisely the opposite when crypto is involved. You DO NOT want security-critical libraries constantly adding fluff for the sake of living on the edge. You want a battle-tested solution known to work _correctly_.

This is a cryptographic library, not an emoticon pack. It will need an update only when something is found to be insecure or broken.

**Comment by foxxyz** [comment]
> This is code, not a banana. I'm not aware of any time-induced breakage, hence closing.

While this is a fun response, the computing environment doesn't stand still. Language advances, deprecations, engine and operating system changes will require maintenance and occasional updates. 

Right now I can't even install the dev dependencies to run the tests, which does warrant attention.

> Actually, it's precisely the opposite when crypto is involved. You DO NOT want security-critical libraries constantly adding fluff for the sake of living on the edge. You want a battle-tested solution known to work correctly.

I don't think they were advocating for adding fluff. I agree that you want to be conservative with regards to making feature changes, but regular maintenance is critical to security.

@dcodeIO If you need support in maintaining this library, let me know and I'd be happy to do so.

**Comment by dev-garcia** [comment]
Hello,

I hope you're doing well!

I saw that you offered to help maintain **bcryptjs**, but didn't receive any response from the creator. Therefore, I’d like to invite you to collaborate on a new project I’ve created, the **cryptography-password-js** library.

This new solution was inspired by **bcryptjs**, but with some improvements that I believe are essential for modern projects:

- **Zero dependencies**, just like **bcryptjs**, but with the addition of **native TypeScript compatibility**.
- Fully **compatible with the latest versions of Node.js**, including the most recent one.
- Focused on **security**, providing a robust and reliable solution for modern **JavaScript** and **TypeScript** projects.
- Designed to offer a **great developer experience**, making integration and usage easier for projects that require high performance and security.

During the benchmark tests, the results were quite positive, and I believe that with your experience, we could accelerate the development and maintenance of the project.

I would be thrilled to have your support! If you're interested, the project is available on GitHub here: [https://github.com/dev-garcia/cryptography-password-js.git](https://github.com/dev-garcia/cryptography-password-js.git)
