### ISSUE TITLE
fallback random number generators considered insecure

### ISSUE THREAD

**Issue by timkuijsten** [dcodeIO/bcrypt.js#16]
I've read a lot of things since the LibreSSL fork about not using a userland CSPRNG, simply because secure randomness can only be assured by the kernel [1][2][3][4].

I'm wondering why these rules would not apply to JavaScript programs. I suspect that this library would be more secure if it by default hard fails if neither Web Crypto nor Nodejs crypto are available, instead of falling back to the "userland" ISAACs PRNG.

[1] http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/
[2] https://news.ycombinator.com/item?id=8034710
[3] http://news.sixgun.org/2014/07/21/linux-kernel-libressl/
[4] http://lwn.net/Articles/606141/

**Comment by wu-lee** [comment]
> If Web Crypto API is available, whatever is specified with setRandomFallback is not used at all.

Can I suggest you document this point? I only spotted it after digging around in the code and finding the link to this issue.
