### ISSUE TITLE
bcrypt.compare ceases unexpectedly

### ISSUE THREAD

**Issue by adrianblynch** [dcodeIO/bcrypt.js#18]
I have a strange issue that I'm trying to debug and I've come to a bit of a wall.

I am using bcrypt for password hashing. Our tests are being run with Mocha and in one of the test suites we are logging in, calling bcrypt.compare multiple times.

One of the tests is failing with an uncaught error. Mocha only give a top level clue as to where the problem is.

Tracing the code I have got to the call to bcrypt.compare:

```
console.log(pw, hash);

bcrypt.compare(pw, hash, function(err, result) {

	console.log("Inside bcrypt.compare()", err, result);

	if (err) {
		return callback(err);
	}

	return callback(null, result);

}, function(t) {
	console.log(t);
});
```

I've simplified the code a little bit but the error (if that's what it is) still persists.

The process callback is added as an aid to debugging and wasn't originally included.

After a few calls of the above code, bcrypt seems to stop partway through camparing.

The `console.log(t);` gets to around a third of the way through and then everything stops.

Output from the previous call is:

```
0
0.102294921875
0.204345703125
0.306640625
0.391845703125
0.48681640625
0.58935546875
0.692138671875
0.79443359375
0.89697265625
0.99951171875
1
```

Output from the failing call is:

```
0
0.097412109375
0.198974609375
0.30029296875
```

The test suite calls bcrypt.compare a total of 16 times, including the failing one. The prior calls have a few that return false by design.

The good news is I can repeat this every time.

I've taken the offending hash and password and they work as expected with a single call to bcrypt.compare.

I thought I might try:

- Reduce the number of calls in the test suite
- Switch to compareSync
- Pull all the hashes and passwords into a test file and run them asyncronously
- Start placing debug code in bcrypt.js
- Switch to another bcrypt module to see if the problem persists.

Any other suggestions?

**Comment by adrianblynch** [comment]
Because it was easy to do, I swapped to using [bcrypt](https://www.npmjs.com/package/bcrypt) and it started to work. Swapping back and the problem persists.

**Comment by dcodeIO** [comment]
Closing this for now. Feel free to reopen it if the error persists. Would also be great to have a snippet including inputs to be able to reliably reproduce this.
