### ISSUE TITLE
[Question] - Why setting number of rounds to 1 is not supported?

### ISSUE THREAD

**Issue by c990802** [dcodeIO/bcrypt.js#19]
While a cost factor of 1 deceives the purpose of bcrypt, I think it makes sense for running automated tests without unnecessarily slowing them down. In my case, a cost factor of 4 run in a test suite with large  pct of tests using bcrypt slowed the whole process down by 39%.
thanks

**Comment by dcodeIO** [comment]
Pretty much every bcrypt library I know of makes this restriction, as did the one this library is based upon. This might have something to do with the internal state requiring this, or be rather arbitrary. Nevertheless, I'd prefer to keep it to make this library work just like the others.

**Comment by c990802** [comment]
cool. makes sense.
thx

**Comment by jbergstroem** [comment]
@dcodeIO my test suite failed when switching between the two libraries because of this. To retain 100% compatibility it might make sense to allow it.
