### ISSUE TITLE
This project is abandoned?

### ISSUE THREAD

**Issue by felipefdl** [dcodeIO/bcrypt.js#22]
Just to me know, I thinking about change node-bcrypt to this one. Do exists better option?

**Comment by julianlam** [comment]
This project is just fine, as far as I know. We use it over at [NodeBB](/nodebb/nodebb) :smile: 

Another alternative is https://github.com/shaneGirish/bcrypt-nodejs, but I have not tried it myself.

**Comment by felipefdl** [comment]
@julianlam I had this question because the last commit is 2 December 2014. So, I installed here and work well. Thank's. The NodeBB is awesome. :)
