### ISSUE TITLE
bcryptjs fails on browser context

### ISSUE THREAD

**Issue by tresdin** [dcodeIO/bcrypt.js#27]
I got the error `Neither WebCryptoAPI nor a crypto module is available. Use bcrypt.setRandomFallback to set an alternative` when I was trying to generate salt with `bcryptjs`. After taking a brief look at the source, I've found that `global` variable is actually not defined on browser context.

**Comment by tresdin** [comment]
Please consider use `self` instead of  `window` object since it's not available on web workers context.

**Comment by dcodeIO** [comment]
Good point, thanks!

**Comment by hqinnus** [comment]
Hi, I'm using bcryptjs in browser, for WCA mode. 
After you change `window` back to `self`, that call of "random(1)" to test random library will always fail. How to resolve it? 
Also the random call inside genSaltSync also cannot identify `self`. It will always prompt error. 
Can you provide a API to define `self`?

**Comment by hqinnus** [comment]
I find the bcrypt.js I download from the source dist folder directly is correct.
But the file I download from the "Downloads" section in the readme has problem. Basically, that lead to this link "https://github.com/dcodeIO/bcrypt.js/archive/master.zip".
I guess this is an outdated file, the readme.md should be updated to reflect updated download link.
