### ISSUE TITLE
Not giving the results from hashSync on Yosemite

### ISSUE THREAD

**Issue by rpgeeganage** [dcodeIO/bcrypt.js#28]
I use the hashSync function on creating the users on my local Mac book. I does not giving the output, instead it waits without any output.
The genSaltSync() function works fine and give the salt.
Please provide assistance regarding this issue.
I have installed node-gyp, python.

**Comment by masonhugus** [comment]
I was having the same problem when I noticed the work factor for the salt was too high. After running some tests a factor of 18 was taking around 50 seconds to generate a hash on my mac. It didn't seem to make much of a difference using sync/async.

**Comment by rpgeeganage** [comment]
I saw that, particular version had infinite loop. It got fixed after reducing the version.

**Comment by faceleg** [comment]
@rpgeeganage should this issue be closed then?

**Comment by Ruffio** [comment]
@dcodeIO this issue can be closed to to inactivity. The originator hasn't answered the question from 2016...
