### ISSUE TITLE
Create a non-doted salt with browserify

### ISSUE THREAD

**Issue by antogerva** [dcodeIO/bcrypt.js#32]
Here's the script:
```javascript
	var bcrypt = require('bcryptjs');
	var isaac= require('isaac');	 
	var mySeed= 0.1;
	isaac.seed(mySeed);
	bcrypt.setRandomFallback(isaac.rand);
	var salt = bcrypt.genSaltSync(12);
	console.log(salt);
```
Here's the result:

	$2a$12$......................

Here's the command line:

	browserify app\myScript.js -o app\myOutput.js -d
	node app\myOutput.js

I need to do this for an offline PhoneGap app. Also, I'm currently using the latest of node, npm, isaac, bcryptjs.
So, how to create a `non-doted` salt with browserify?

**Comment by dcodeIO** [comment]
`bcrypt.setRandomFallback(isaac.rand);` is wrong, see: https://github.com/dcodeIO/bcrypt.js#setrandomfallbackrandom

**Comment by antogerva** [comment]
Ok, I thought isaac.js could provide a function for bcrypt.setRandomFallback.
So my assumption was wrong?

If that's the case, then since I just figured that this works:
```javascript
bcrypt.setRandomFallback(crypto.randomBytes);
```
I guess, I could go ahead with that.
Thanks

**Comment by dcodeIO** [comment]
You can use any CSPRNG, but that's not the point. You have to make sure that you provide a proper argument to `setRandomFallback`. It takes a function with a single argument, which is the number of bytes to generate, and returns an array of bytes. `isaac.rand` does not fit that function signature, but you can of course craft your own function with that signature that uses isaac. Also, when using isaac, it is mandatory to make sure that it is properly seeded using a strong source of entropy.

`crypto.randomBytes` (if that's from node) on the other hand fits the required signature. However, I am not quite sure how this is implemented within a phonegap app.

**Comment by antogerva** [comment]
> `crypto.randomBytes` (if that's from node) on the other hand fits the required signature.
Well, now with that piece of information, I managed to solve the issue. Thanks you for the help!
