### ISSUE TITLE
saltrounds and hash

### ISSUE THREAD

**Issue by eugen35** [dcodeIO/bcrypt.js#34]
hello!
I am new in hashing of passwords. Just have readed some articles about it and some things from them  not match for your api. 
The mentioned things
1)*\* in articles**: hash=hashFunc(password+uniqueSalt). And if salt is unique, so i need to save in DB hash and unique salt
**by you**: hash=hashFunc(password+uniqueSalt). But as result hash="salt+something". This something is hash or not? So i dont need save in DB hash and uniqueSalt, i.e. salt saving with hash in one string?
2) **in articles**: rounds quantity is used by gen hash
**by you**: rounds quantity is used by gen salt

Can you explain mentioned difference?

**Comment by wedneyyuri** [comment]
This question may help you: 
http://stackoverflow.com/questions/6832445/how-can-bcrypt-have-built-in-salts

**Comment by dcodeIO** [comment]
See also: [bcrypt](https://en.wikipedia.org/wiki/Bcrypt)

**Comment by Ruffio** [comment]
This question should be closed.
