### ISSUE TITLE
What is hash algorithm?

### ISSUE THREAD

**Issue by wzup** [dcodeIO/bcrypt.js#35]
Tables usually have `password_hash_algorithm` column. Any chances to know what hash algorithm is used by bcrypt.js when `bcrypt.hash`? What can I save in that column? For the situation when `bcrypt.js` is not possible to use I want to be able to check passwords.

**Comment by wedneyyuri** [comment]
Maybe it helps http://stackoverflow.com/questions/6832445/how-can-bcrypt-have-built-in-salts

**Comment by dcodeIO** [comment]
The output of bcrypt.js is compatible to any other [bcrypt](https://en.wikipedia.org/wiki/Bcrypt) implementation (there are plenty for pretty much any programming language). The hashing algorithm here is bcrypt, which in turn is based on blowfish.

**Comment by Ruffio** [comment]
This was a question that has been answered. It should be closed...
