### ISSUE TITLE
Update Repo to Version 2.4.0

### ISSUE THREAD

**Issue by rousos87** [dcodeIO/bcrypt.js#41]
Hello

Can you please update repo to the newest version (2.4.0) so we be able to install it via npm?

Thank you

**Comment by hillerstorm** [comment]
Works when using `"dcodeIO/bcrypt.js"` as package version but a published version on npm would be great 👍 
Even a prerelease is acceptable 😄

**Comment by sylvainlap** [comment]
+1

**Comment by dcodeIO** [comment]
Besides an initial promise support implementation, there is nothing really new in 2.4.0. Do you need this for promises? If so: Did you test it and can confirm that it is doing what it should?

**Comment by andreolvr** [comment]
I was trying to use promises, took me time to realize that the error was because i was using version 2.3.

**Comment by dcodeIO** [comment]
Would be great if you could test-run 2.4.0 from master and let me know if it is doing its job with promises or not. Will publish then!

**Comment by andreolvr** [comment]
I'm using 2.4 and it works fine for me with promises.

**Comment by kikoanis** [comment]
Works fine for me as well.

**Comment by nickdbush** [comment]
All good. Even if you're not going to push yet, could you at least point this out in the README for lazy people (like me), because I just spent half an hour head-scratching and tea-drinking. Thanks!

**Comment by dcodeIO** [comment]
It's now on npm
