### ISSUE TITLE
Unable to compare password

### ISSUE THREAD

**Issue by wsfuller** [dcodeIO/bcrypt.js#45]
So I've looked over the documentation for a couple of hours and been looking over examples and tutorials for quite sometime and nothing seems to work. All I want to do is salt and hash a users password and store it. Then have the user login, compare the passwords, and then send a JSON Web Token. 

Test Credentials:
email: test@test.com
password: password

**user.routes.js**

```
var express     = require('express');
var router      = express.Router();
var jwt         = require('jsonwebtoken');
var bcrypt      = require('bcryptjs');
var config      = require('../config/database');

// POST create user
...
bcrypt.genSalt(10, function(err, salt) {
    bcrypt.hash("superSecret", salt, function(err, hash) {
      user.password = hash;
      user.save();
      res.json({success: true, message: 'Create user successful'});
    });
  });
...

// POST login
...
bcrypt.compare(req.body.password, "superSecret", function(err, res) {
    if(user.password != req.body.password){
      console.log('password incorrect');
      //res.send('password incorrect');
    } else {
      console.log('password is correct send JWT');
      //res.send('password correct send JWT');
    }
  });
...
```

I'm not quite sure what actually is supposed to be passed in the `compare` method. The documentation has `bcrypt.compare("B4c0/\/", hash, function(err, res){..})` but hash is undefined. 

So should I be declaring `var hash = ...` initially and if I am doesn't that defeat the purpose of `bcrypt.hash("superSecret", salt, function(err, hash){...}); from the Create user?

**Comment by dcodeIO** [comment]
If I understand your setup correctly you are only encrypting the user's password on the server side, while accepting plaintext inputs over the network. In this case, `bcrypt.compare` takes the plaintext password as the first argument, testing it against the hash that you previously stored in `user.password`, which is the second argument.

**Comment by wsfuller** [comment]
Thanks for the response, so that's where I'm having the must trouble.

    var hash = 'superSecret';
    ...
    bcrypt.compare(req.body.password, hash, function(err, res) {
      // not sure what to do here
      if(user.password != req.body.password){
            res.send('failure message'); //ERROR unresolved method or function
      } else {
        res.send({JWT}); //ERROR unresolved method or function
      }
    });

So I'm staring at two errors. One being the comparison is always going to be wrong where it's comparing plaintext versus a hashed password. I don't quite understand how this method is supposed to work. Second being I'm unable to send a response. The second, I could set a callback function based on a boolean like `var passwordStatus = '';` and depending on the conditional I could set that variable to true or false.

**Comment by ribbibisaria** [comment]
Taking your example and making changes accordingly for correct results
var express     = require('express');
var router      = express.Router();
var jwt         = require('jsonwebtoken');
var bcrypt      = require('bcryptjs');
var config      = require('../config/database');

// POST create user
...
bcrypt.genSalt(10, function(err, salt) {

//You need to remember 'superSecret' is supposed to be the password taken from user
// for example req.body.password instead of 'superSecret' . This is just to clarify
 bcrypt.hash("superSecret", salt, function(err, hash) {
    user.password = hash;
      user.save();
      res.json({success: true, message: 'Create user successful'});
    });
  });
...

// POST login
...
//for compare just fetch the password as you saved it from previous createUser
//Basically find and fetch the user you saved
//in place of "superSecret" use the hashed password you have fetched AS IS
//Eg. bcrypt.compare(req.body.password, userFound.hashedPassword, function(err, response) { 
//this will return response=true or response=false accordingly after comparing
//Id suggest changing  'res' to 'response' since we use term res for our own response  

bcrypt.compare(req.body.password, "superSecret", function(err, res) {
    if(user.password != req.body.password){
      console.log('password incorrect');
      //res.send('password incorrect');
    } else {
      console.log('password is correct send JWT');
      //res.send('password correct send JWT');
    }
  });
...

**Comment by anantnema** [comment]
I am storing the hashed password in the mongodb and then trying to compare the password in db with the user input password but this function is always returning false no matter whatever be the case.


    `module.exports.comparePassword = function(candidatePassword, hash, callback){
      // Load hash from your password DB.

    bcrypt.compare(candidatePassword, hash, function(err, isMatch) {
      // res === true
      if(err) throw err;
      else return callback(null, isMatch);
    });
    }`


getUserByUsername is working fine but the compare password is returning always "Invalid password"


     `passport.use(new LocalStrategy(
        function(username, password, done) {
          User.getUserByUsername(username, function(err, user){
             if(err) throw err;
             if(!user){
             return done(null, false, {message: 'Unknown User'});
          }

         User.comparePassword(password, user.password, function(err, isMatch){
            if(err) throw err;
         //(this isMatch is always false)
            if(!isMatch) {

            return done(null, false, {message: 'Invalid password'});
          }
         return done(null, user);
        });
      });
     }));`

**Comment by Ruffio** [comment]
@wsfuller is this still an issue or can it be closed?

**Comment by wsfuller** [comment]
@Ruffio This can be closed
