### ISSUE TITLE
Should `catch` be used for non-match with promise?

### ISSUE THREAD

**Issue by josephrocca** [dcodeIO/bcrypt.js#49]
Regarding this promise example in the readme:
```javascript
bcrypt.compare("mypassword", hash)
.then(() => {console.log("Comparison was true")})
.catch(() => {console.log("Comparison was false")})
```

Is it a good idea to call `catch` for a non-match? It isn't really an error if the comparison was false - is it? I'd have expected something like:
```javascript
bcrypt.compare("mypassword", hash)
.then((match) => {
  if(match) console.log("Comparison was true");
  else console.log("Comparison was false");
});
```

If an error is thrown for a non-match, then (using `async/await`) we need to do this:
```javascript
let match;
try {
  await bcrypt.compare("mypassword", hash);
  match = true;
} catch() {
  match = false;
}
```

Rather than simply:
```javascript
let match = await bcrypt.compare("mypassword", hash);
```

I might have misunderstood the readme though - haven't actually used this lib yet. Cheers :)

**Comment by kailniris** [comment]
https://github.com/dcodeIO/bcrypt.js/issues/51
