### ISSUE TITLE
compare always returns success

### ISSUE THREAD

**Issue by EvaldasVasiliauskas** [dcodeIO/bcrypt.js#51]
no matter what password I pass, compare always returns success. Am I doing something wrong?
Here's an example of very primitive app:

```
var bcrypt = require('bcryptjs');

var mypass = 'B4c0/\/';
var mysalt = '';
var myhash = '';

mysalt = bcrypt.genSaltSync(10);
myhash = bcrypt.hashSync(mypass, mysalt);

bcrypt.compare(mypass + 'a', myhash)
.then(() => {console.log("Comparison was true")})
.catch(() => {console.log("Comparison was false")});
```

OS: Win x64
npm: 4.0.5
node: 7.4.0

**Comment by dcodeIO** [comment]
I believe the example on the README is incorrect:

```js
bcrypt.compare(mypass + 'a', myhash)
.then((res) => {console.log("Comparison was: " + res)})
.catch(() => {console.log("Exception thrown")});
```

**Comment by EvaldasVasiliauskas** [comment]
Thanks

**Comment by AtharvaPanegai** [comment]
Still facing the same issue 

while creating user I hash the password like this
userSchema.pre("save", async function (next) {
  if (!this.isModified("password")) {
    return next;
  }
  const salt = bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
});

 and compare it like this

userSchema.methods.isPasswordValid = function (usersendPassword) {
  return bcrypt.compare(usersendPassword, this.password);
};

can you tell me where I'm going wrong I'm getting true everytime
