### ISSUE TITLE
Is it possible to set the number of rounds for hashing?

### ISSUE THREAD

**Issue by clare-aire** [dcodeIO/bcrypt.js#52]
Firstly, thank you for saving my bacon with this library! Having suggested bcrypt last week and then totally forgetting I was in React land and not node, a panic-Google search on Friday returned this! Yes! :)

My question is: I see that I can control the number of rounds used to generate a salt, but I can't see if it's possible to set the rounds for actually hashing. Is this configurable anywhere? (i.e. I can getRounds(hash) but not setRounds().

Thanks

Clare

**Comment by dcodeIO** [comment]
Unfortunately, this isn't configurable currently. It's hard-coded [here](https://github.com/dcodeIO/bcrypt.js/blob/master/src/bcrypt/impl.js#L13).

**Comment by clare-aire** [comment]
Ah thank you for the quick response :) I know more than I did this morning, which is there are 10 rounds. Cheers!

**Comment by Ruffio** [comment]
@clare-aire can this issue be closed?

**Comment by clare-aire** [comment]
@Ruffio Ah yes it can, sorry I forgot thank you.
