### ISSUE TITLE
compareSync with specified salt value

### ISSUE THREAD

**Issue by parnurzeal** [dcodeIO/bcrypt.js#56]
My understanding is that salt value is also required to compare hash properly.
Why is there none in the compareSync parameters?

Usecase taken from https://crackstation.net/hashing-security.htm: 
[To Store a Password]
1. Generate a long random salt using a CSPRNG.
2. Prepend the salt to the password and hash it with a standard password hashing function like Argon2, bcrypt, scrypt, or PBKDF2.
3. Save both the salt and the hash in the user's database record.

[To Validate a Password]
1. Retrieve the user's salt and hash from the database.
2. Prepend the salt to the given password and hash it using the same hash function.
3. Compare the hash of the given password with the hash from the database. If they match, the password is correct. Otherwise, the password is incorrect.

**Comment by dcodeIO** [comment]
That's because the function takes the full hash that also includes logRounds and salt - instead of specifying each as its own parameter.

> For example, the shadow password record $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy specifies a cost parameter of 10, indicating 210 key expansion rounds. The salt is N9qo8uLOickgx2ZMRZoMye and the resulting hash is IjZAgcfl7p92ldGxad68LJZdL17lhWy. ([ref](https://en.wikipedia.org/wiki/Bcrypt))

**Comment by parnurzeal** [comment]
Thanks for the clarification!
