### ISSUE TITLE
random

### ISSUE THREAD

**Issue by annslittleflower** [dcodeIO/bcrypt.js#61]
![image](https://cloud.githubusercontent.com/assets/18059716/26255821/881a295a-3cc3-11e7-8d66-ed1336fde50d.png)
getting this error, but everything works if new uintarray is replaced with new array
please answer what is wrong

**Comment by dcodeIO** [comment]
Hmm, this doesn't look like any code provided by this package.

**Comment by annslittleflower** [comment]
it is not link to your package?
https://www.npmjs.com/package/react-native-bcrypt

**Comment by dcodeIO** [comment]
This package is https://www.npmjs.com/package/bcryptjs

**Comment by dcodeIO** [comment]
Closing this for now. Feel free to reopen if necessary.

**Comment by pewh** [comment]
Is it compatible with React Native?
