### ISSUE TITLE
compareSync throwing error

### ISSUE THREAD

**Issue by BenReilly** [dcodeIO/bcrypt.js#65]
in a mongoose schema
```
const bcrypt = require('bcryptjs');

//schema definition, etc

UserSchema.methods.comparePassword = function(candidatePassword) {
    // because this is called as a method of u, the password will be the result
    if (bcrypt.compareSync(candidatePassword, this.password)) {
        return true;
    };
    return false;
};
```
elsewhere calling it:
```
let salt = bcrypt.genSaltSync(10),
    u = new user({
          username: 'someUser',
          password: bcrypt.hashSync('astring', salt)
    });
authentic = u.comparePassword('astring');
```
this gives me ``Error: Illegal arguments: string, object`` in the line that calls ``bcrypt.compareSync``

some notes: in this example, when ``comparePassword`` is called ``candidatePassword`` will be 'astring'. Since it is called as a method of` ``u``, that means ``this.password`` will be the result of the hashSync function, which a console.log shows me is a buffer.  Seems pretty straightforward to me. What am I doing wrong?

**Comment by BenReilly** [comment]
OK, so the problem was in my schema definition, which made the `password` property a Buffer (artifact from playing with libsodium). Changing that property to a String fixes everything.

**Comment by Ruffio** [comment]
@BenReilly if this can be closed, please close it :-)

**Comment by Anthony4m** [comment]
same error how do i fix it

const LocalStrategy = require("passport-local").Strategy;

const mysql = require('mysql');
const bcrypt = require('bcryptjs');
const dbconfig = require('./database');
const connection = mysql.createConnection(dbconfig.connection);

connection.query('USE ' + dbconfig.database);

module.exports = function(passport) {
 passport.serializeUser(function(user, done){
  done(null, user.id);
 });

 passport.deserializeUser(function(id, done){
  connection.query("SELECT * FROM admin WHERE id = ? ", [id],
   function(err, rows){
    done(err, rows[0]);
   });
 });

 passport.use(
  'local-signup',
  new LocalStrategy({
   usernameField : 'username',
   passwordField: 'password',
   passReqToCallback: true
  },
  function(req, username, password, done){
   connection.query("SELECT * FROM admin WHERE username = ? ", 
   [username], function(err, rows){
    if(err)
     return done(err);
    if(rows.length){
     return done(null, false, req.flash('signupMessage', 'That is already taken'));
    }else{
     const newUserMysql = {
      username: username,
      password: bcrypt.hashSync(password, null, null)
     };

     const insertQuery = "INSERT INTO admin (username, password) values (?, ?)";

     connection.query(insertQuery, [newUserMysql.username, newUserMysql.password],
      function(err, rows){
       newUserMysql.id = rows.insertId;

       return done(null, newUserMysql);
      });
    }
   });
  })
 );

 passport.use(
  'local-login',
  new LocalStrategy({
   usernameField : 'username',
   passwordField: 'password',
   passReqToCallback: true
  },
  function(req, username, password, done){
   connection.query("SELECT * FROM admin WHERE username = ? ", [username],
   function(err, rows){
    if(err)
     return done(err);
    if(!rows.length){
     return done(null, false, req.flash('loginMessage', 'No User Found'));
    }
    if(!bcrypt.compareSync(password, rows[0].password))
     return done(null, false, req.flash('loginMessage', 'Wrong Password'));

    return done(null, rows[0]);
   });
  })
 );
};
