### ISSUE TITLE
example for implementation in React Native

### ISSUE THREAD

**Issue by assafb81** [dcodeIO/bcrypt.js#68]
Hi,
I am using RN version 0.45.1,
And I am trying to write an application in React Native which receives data in JSON format and I want to add digital signature to data in order to verify the message.
currently I am only interested in the application side, meaning - only the verification of the data.
The data, json object, is stored in Amazon S3 and I am planning to sign it with online tool for now.

how can I do this?

Thanks,

**Comment by TheMaverickProgrammer** [comment]
it's exactly the same

**Comment by Ruffio** [comment]
I think you would come further by asking this question on stackoverflow or similar site. Github is only for 'issues' with the code, not about how to use it implementation. This question should be closed...

**Comment by assafb81** [comment]
I finally used different package. 
The current package did not match my requirements.

**Comment by TheMaverickProgrammer** [comment]
It's literally the same way you'd use it in node.
