### ISSUE TITLE
Base64 encoding/decoding use native atob/btoa if available

### ISSUE THREAD

**Issue by Ruffio** [dcodeIO/bcrypt.js#72]
Cool project, that I'm going to use :-)

I have been looking thru the code and can see that some kind of Base64 encoding/decoding is used. Would it be an idea to use atob/btoa if available with a fallback to the currently implemented method if not? According to 'Can I Use' then all major browsers have these implemented and supported. It has been for many versions (https://caniuse.com/#search=atob):

![image](https://user-images.githubusercontent.com/1877612/30911076-7534bd20-a387-11e7-8bf0-53428fb5423f.png)

**Comment by dcodeIO** [comment]
bcrypt's base64 alphabet differs from what is considered the standard. Hence it has its own implementation.

**Comment by Ruffio** [comment]
Is that because bcrypt was originally developed before 'the standard' became the standard ?

**Comment by dcodeIO** [comment]
I am not aware of the historical background, unfortunately.
