### ISSUE TITLE
process.nextTick still starves the event loop

### ISSUE THREAD

**Issue by spion-h4** [dcodeIO/bcrypt.js#80]
Hi! I noticed bcrypt.js uses `process.nextTick` in node to delay the calculation.

Unfortunately, repeated calls to nextTick will still starve the event loop: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#process-nexttick

nextTick is unfortunately badly named, it should've been called 'endOfThisTick`.

Can we switch to `setImmediate` instead?

**Comment by spion-h4** [comment]
Never mind, I took a closer look the condition does pick `setImmediate` when its available. So this is not an issue in environments where thats present (although it might still  be an issue in older node versions).

**Comment by lionel-rowe** [comment]
This is still an issue in environments with `process.nextTick` but no `setImmediate` (e.g. browser with polyfilled Node `process`). Is there any reason to ever prefer `process.nextTick`?
